[package]
name = "gquest_core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.0", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }

log = "0.4.22"
env_logger = "0.11.5"
topo_sort = "0.4.0"
serde_json = "1.0.125"
serde = "1.0.208"
futures = "0.3.30"
tabled = "0.16.0"
regex = "1.10.6"
duct = "0.13.7"

