use clap::{ArgAction, Args, Parser, Subcommand};

use gquest_core::db_handler::{graph_database::*, sqlite_handler::*};

const DEFAULT_URL: &str = "sqlite://gquest.db";

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct CliArg {
    #[command(subcommand)]
    cmd: Modes
}

#[derive(Subcommand, Debug, Clone)]
enum Modes {
    /// Initialise a project/database to work with
    Init {
        #[command(subcommand)]
        input_method : DatasetChoice,
        #[command(flatten)]
        path : DatabasePath,
    },
    /// Add graphs to an already existing project  
    Add {
        #[command(flatten)]
        path : DatabasePath
    },
    /// Compute invariants from a dataset
    Compute {
        #[command(flatten)]
        path : DatabasePath,
        #[clap(default_value = "None")]
        dependencies_file: std::path::PathBuf,
        /// The list of programs to call
        #[clap(long, short, value_parser, num_args = 1.., value_delimiter = ' ')]
        programs: Vec<std::path::PathBuf>,
    },
    /// Delete a table from a dataset
    Delete {
        /// The name of the table/invariant to delete
        #[clap()]
        table_name: String, 
        #[command(flatten)]
        path: DatabasePath,
    },
    /// Send querries to a database
    Query {
        /// Do not output the result
        #[clap(short='u', long, action=ArgAction::SetTrue)]
        hide_output : bool,
        /// Do not saves the result
        #[clap(short, action=ArgAction::SetTrue)]
        do_not_save : bool,
        /// The query to ask the database
        #[clap()]
        formula : String,
        #[command(flatten)]
        path : DatabasePath,
    },
    /// Show a summary of a project
    Summary {
        #[command(flatten)]
        path : DatabasePath
    },
}


#[derive(Args, Debug, Clone)]
struct DatabasePath {
    /// The url to the database to connect to
    #[clap(default_value = DEFAULT_URL)]
    url: String  
}



#[derive(Args, Debug, Clone)]
struct GengArgs {
    /// The mininum and/or maximum order of the graphs to generate
    #[clap(name("order|min:[max] order"), long("order"), short('o'), value_delimiter = ':')]  // TODO We should allow the user to exclude value from range
    order : Vec<Option<String>>,
    /// The mininum and/or maximum number of edges of the graphs to generate
    #[clap(name("edges|min:[max] edges"), long("edges"), short('e'), value_delimiter = ':')]
    edge : Vec<Option<String>>,
    
    /// The parameters to give to geng in oder to generate a graph of an order
    #[clap(long, short)]
    params : String,

    // Shows the graphs generated by geng
    //#[clap(long, short, action=ArgAction::SetFalse)]
    //show_graphs : bool
    
}
   



#[derive(Subcommand, Debug, Clone)]
enum DatasetChoice {
    Geng {
        #[command(flatten)]
        args : GengArgs
    },
    Import {
        #[command(flatten)]
        args : ImportArgs
    }
}




#[derive(Debug, clap::Args, Clone)]
#[group(required = false, multiple = false)]        // This will stop the user from adding multiple arguments, meaning we do not have to check
struct ImportArgs {
    /// The file were the dataset is stored
    #[clap(short, long)]
    file: Option<String>,
    /// Read from the standart input (default) 
    #[clap(short, long, action=ArgAction::SetTrue)]
    read_stdin : bool,
}



#[derive(Args, Debug, Clone)]
struct  DatabaseInfoPath {
    /// The path or url to the database to access
    #[clap(short,long)]
    database_path_url: String,
}


#[tokio::main(flavor = "current_thread")]
async fn main() {
     
    let args = CliArg::parse();
    
    match args.cmd {
        Modes::Init { path, input_method } => init(path, input_method).await,
        Modes::Add { path } => todo!(),
        Modes::Compute { path, dependencies_file, programs } => todo!(),
            
        Modes::Delete { path, table_name } => todo!(),
        Modes::Query { hide_output, do_not_save, formula, path } => todo!(),
        Modes::Summary { path } => todo!(),
    }
}


async fn init(path: DatabasePath, choice: DatasetChoice)
{
    // Create workspace
    //let w : Workspace<SqliteGraphDatabase> = Workspace::init_workspace(&path.url).await;
    // Only one can be chosen at a time
    match choice {
        DatasetChoice::Geng { args } => {
            println!("args: {:?}", args);
            if args.order.len() == 1 {
                println!("The only order to generate is {:?}", args.order[0])
            }
            // Too many arguments
            if args.order.len() > 2 {
                panic!("Too many arguments for the \"order\" option");
            }
        },
        DatasetChoice::Import { args } => todo!(),
    }
    // Close workspace
    //w.close_workspace().await;
}