// Handles spaces and tabs, which are skipped during parsing.
WHITESPACE = _{ " " | "\t" }

// Combines all queries into one for ease of parse
query = { (if_query | extremal_condition) ~ EOI }

// Rules simply used for unit tests to force an input to end with EOI 
extremal_condition_eoi = _{ extremal_condition ~ EOI }
if_query_eoi = _{ if_query ~ EOI }


// example : d > 3 -> conj1 = 1
// or : 	 if d > 3 then conj = 1
if_query      =  { (if_then_query | if_shortened) }
if_then_query = _{ if ~ extremal_condition ~ then ~ condition }
if_shortened  = _{ extremal_condition ~ if_then_arrow ~ condition }

// Extremal Condition : max(p_qn) or max(p_qn: n) or even max(p_qn: n, m)
extremal      = { extremal_func ~ "(" ~ identifier ~ (":" ~ identifier ~ ("," ~ identifier)*)? ~ ")" }
extremal_func = { max_func | min_func }

// 3 tokens -> extremal + condition
// 2 tokens -> /
// 1 token  -> either an extremal selection or a condition.
extremal_condition = { (extremal ~ (and_op ~ condition)? | condition) }
condition          = {
    comparison ~ binary_op ~ condition
  | comparison
}
binary_op          = { and_op | or_op | xor_op | implication_op | equivalence_op }

comparison = {
    expr ~ comp_operator ~ expr
  | "(" ~ condition ~ ")"
  | not_comparison
  | identifier
}

// !inv or !(inv = 1)
// Special case of inv to not force parenthesis: !(x) == !x
not_comparison = { not_op ~ (identifier | "(" ~ condition ~ ")") }

comp_operator = {
    equal
  | not_equal
  | less_equal
  | less
  | greater_equal
  | greater
}

// _________ MATH _________

primary = _{ primitif | "(" ~ expr ~ ")" }
atom    = _{ atom_function? ~ primary }

atom_function = _{ floor | ceil | sqrt | abs | negation }
floor         =  { "floor" }
ceil          =  { "ceil" }
sqrt          =  { "sqrt" }
abs           =  { "abs" }
negation      =  { "-" }

bin_op       = _{ add | subtract | exponent | multiply | floor_divide | divide | modulo }
add          =  { "+" }
subtract     =  { "-" }
exponent     =  { "**" | "^" }
multiply     =  { "*" }
floor_divide =  { "//" }
divide       =  { "/" }
modulo       =  { "%" }

expr = { atom ~ (bin_op ~ atom)* }

// _________ OTHERS _________

primitif = { identifier | value }

// Either a number (-1.212) or a string value ("a value")
value = { number | string }

// A value representing an identifier (must start with a letter)
identifier = @{ ASCII_ALPHA ~ valid_ascii* }

string        =  { double_quotes ~ valid_ascii+ ~ double_quotes }
double_quotes = _{ "\"" }

number      =  { ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
valid_ascii = _{ ASCII_ALPHANUMERIC | "_" }

max_func = { "max" }
min_func = { "min" }

equal         = { "=" | "==" }
not_equal     = { "!" ~ "=" | "≠" }
less_equal    = { "<" ~ "=" | "≤" }
less          = { "<" }
greater_equal = { ">" ~ "=" | "≥" }
greater       = { ">" }

if_then_arrow = _{ "->" }
if            = _{ "if" }
then          = _{ "then" }

and_op =  { "and" | "∧" }
or_op  =  { "or" | "v" }
xor_op  =  { "xor" | "⊕" | "⊻" }
implication_op =  { "==>" }
equivalence_op =  { "<==>" | "iff" }
not_op = _{ "not" | "!" }
